### ISSUE TITLE
LDFLAGS need to refer to ncursesw rather than the non-wide ncurses

### ISSUE THREAD

**Issue by markdingo** [seehuhn/go-ncurses#2]
In ncurses.go there is a CGO line to define the curses library to load. Specifically:

// #cgo LDFLAGS: -lncurses

My tests on modern Debian and FreeBSD show that this now needs to be:

// #cgo LDFLAGS: -lncursesw

to compile successfully.

Have others come across this issue?

It may be that the older library reference is needed for other platforms, in which case this needs to be conditional. But that's an implementation detail.

**Comment by seehuhn** [comment]
Hi Mark, can you try the most recent commit 8eb75318a50c6 to see whether this fixes the issue?  It still works on my Mac (which needs -lncurses), but with a bit of luck it should now use -lncursesw everywhere else.

**Comment by markdingo** [comment]
> Hi Mark, can you try the most recent commit [8eb7531](https://github.com/seehuhn/go-ncurses/commit/8eb75318a50c6c9c90ca5d45b7eb5496665c6ba3) to see whether this fixes the issue? It still works on my Mac (which needs -lncurses), but with a bit of luck it should now use -lncursesw everywhere else.

Looks good. See comments in https://github.com/seehuhn/go-ncurses/pull/1#issuecomment-800704430

Thanks for the quick response!

**Comment by seehuhn** [comment]
I believe this is now fixed.
