### ISSUE TITLE
Fatal error: ncurses.h no such file or directory

### ISSUE THREAD

**Issue by lordofscripts** [seehuhn/go-ncurses#4]
Wrote the necessary `ncurses` package code on my application and included the import as "`seehuhn.de/go/ncurses`". Also performed the go get command and up to then no error.

Then when I tried to compile the app in the cmd directory that uses NCurses, I got this go compilation error:

```
    golang.org/x/sys/internal/unsafeheader
    golang.org/x/sys/unix
    seehuhn.de/go/ncurses
  		Module seehuhn.de/go/ncurses 

		[ FILE  ../pkg/mod/seehuhn.de/go/ncurses@v0.2.0/attrs.go  ]
../pkg/mod/seehuhn.de/go/ncurses@v0.2.0/attrs.go:19@11:
     fatal error  ncurses.h  No such file or directory
       19 | // #include <ncurses.h>
          |           ^~~~~~~~~~~
    compilation terminated.
```

I have downloaded other modules that required compilation (CGO) and never had an issue, but this one crashed and burned. I am on a Linux Debian (Raspbian).

**Comment by seehuhn** [comment]
Hmmm, I'm not sure what the problem is here.  Do you have `ncurses` installed?  Where is the "ncurses.h" header on your system?

**Comment by lordofscripts** [comment]
> Hmmm, I'm not sure what the problem is here. Do you have `ncurses` installed? Where is the "ncurses.h" header on your system?

On my RPI I don't do any C development, just GO & sometimes Python. I can use CGO so I think some of the C stuff is there. I don't see any ncurses directory or ncurses.h file in /usr/include/* I guess a missing dependency?

**Comment by rpoe** [comment]
Now the library compiles for me on Liinux.
Can you please publish the new version to the go repository?
When including it, still the old version is retrieved by go. Thanks.

**Comment by lordofscripts** [comment]
> Now the library compiles for me on Liinux. 

It doesn't on Raspberry Pi (Debian). I guess ncurses development is not installed by default, so mine doesn't have it and it is a dependency that needs to be resolved.

> Can you please publish the new version to the go repository? When including it, still the old version is retrieved by go. Thanks.

Well, I decided to drop the use of `go-ncurses` as it was not included. I decided to build a Go Fyne app instead. Sorry.

**Comment by neochar** [comment]
In Ubuntu it was fixed by installing `libncurses-dev`:

`$ sudo apt install libncurses-dev`
